blank_issues_enabled: true
contact_links:
  - name: Ask a question on how to use template-exercisme
    about: For general-purpose questions and answers, see the Discussions section.
    url: https://github.com/MathieuSoysal/Exercism-Rust-Template/discussions